[package]
name = "texel"
version = "0.1.1"
authors = ["Ales Katona <ales@katona.me>"]
edition = "2018"
description = "ASCII art text editor"
license = "GPL-3.0-or-later"
repository = "https://github.com/almindor/texel"
keywords = ["text", "ascii", "editor", "art", "ascii-art"]
readme = "README.md"
categories = ["text-editors", "multimedia::images"]

[dependencies]
big_enum_set = { version = "0.1.5", features = ["serde"] }
dirs = "2.0.2"
libflate = "0.1.27"
ron = "0.5.1"
serde = "1.0.104"
serde_derive = "1.0.104"
specs = "0.15.1"
termion = "1.5.4"
texel_types = { version = "1.1.0", features = ["ecs_specs", "serde_support"] }
