[package]
name = "texel"
version = "0.1.0"
authors = ["Ales Katona <almindor@gmail.com>"]
edition = "2018"

[dependencies]
termion = "1.5.3"
ron = "0.5.1"
serde = "1.0.101"
serde_derive = "1.0.101"
specs = "0.15.1"
