[package]
name = "texel"
version = "0.1.0"
authors = ["Ales Katona <almindor@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
libflate = "0.1.27"
ron = "0.5.1"
serde = "1.0.102"
serde_derive = "1.0.102"
specs = "0.15.1"
termion = "1.5.3"
