[package]
name = "texel"
version = "0.1.1"
authors = ["Ales Katona <ales@katona.me>"]
edition = "2018"
description = "ASCII art text editor"
license = "GPL-3.0-or-later"
repository = "https://github.com/almindor/texel"
keywords = ["text", "ascii", "editor", "art", "ascii-art"]
readme = "README.md"
categories = ["text-editors", "multimedia::images"]

[dependencies]
big_enum_set = { version = "0.1.5", features = ["serde"] }
crossterm = { version = "0.14.2", optional = true }
dirs = "2.0.2"
legion = "0.2.1"
libflate = "0.1.27"
rand = "0.7.3"
ron = "0.5.1"
serde = "1.0.104"
serde_derive = "1.0.104"
termion = { version = "1.5.4", optional = true }
texel_types = { version = "2.0.0", features = ["serde_support"] }

[features]
default = ["crossterm"]
ion = ["termion"]
